version: "3"
services:
  app:
    build: ./
    links:
      - db
    ports:
      - "8080:8080"

  db:
    image: mysql:8.0.21
    ports:
      - "30000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db_models:/docker-entrypoint-initdb.d/:ro